main : com.ohmona.main.Main
name : plugin
version : 1.0.0
author : ohmona
api-version : 1.13
description  : this is my experience point system
commands :
  he:
    description: test
    usage: /test
  ex: