name : plugin
version : 1.0.0
main : com.ohmona.exp.Main
author : ohmona
api-version : 1.13
description  : this is my experience point system
commands :
  he:
    description: test
    usage: /test
  ex:
  gradeupitem: